version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-py36
      - test-py35
jobs:
  test-py36: &test-template
    docker:
      - image: circleci/python:3.6
    environment:
      TOX_ENV: py36
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
          - v2-dependencies-
      - run:
          name: run tox
          command: tox --notest -e $TOX_ENV
      - save_cache:
          paths:
            - ./.tox
          key: v2-dependencies-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
  test-py35:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
    environment:
      TOX_ENV: py35
